### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by CCYChongyanChen** [LukasAdamowicz/RespiratoryRateEstimation#2]
Hi, LukasAdamowicz, I am wondering if you are willing to share  the structure of the "sample_ecg.csv "dataset with me? I have tried to run it with my own dataset but failed. I know that the "t" represents "time" and v represents "Voltage" and I change them into "array".<br>Many thanks!

**Comment by LukasAdamowicz** [comment]
Structure is two columns in the CSV file, one with timestamps (milliseconds), one with voltages (mV).

Example:

Time (ms), Voltage (mV)
1500023032341,0.01
1500023032541,0.17
1500023032741,0.024
...

**Comment by CCYChongyanChen** [comment]
Thank you!
